elementary/docs

writing-apps/hello-world.md

**Before**: 
We also must give our window a default size so that is does not appear...
**After**:
We also must give our window a default size so that **it** does not appear...

Fix typo in Hello World > Gtk.application

---

appcenter/publishing-updates.md

We should probably double-check the rest of the wiki, then retire it…

Publishing Updates: Update to match Houston Wiki

---

apis/state-saving.md

Fix missing parts of gsettings and add code example

---

writing-apps/code-style.md

Be consistent with our own advice

Use two-space indentation in XML example

---

writing-apps/hello-world.md
writing-apps/untitled/README.md
writing-apps/untitled/the-build-system.md
writing-apps/untitled/translations.md

Fixes #27 
And some updates while we're here

Link to full code examples

---

apis/actions.md

This covers:
* GLib.SimpleAction
* Action accelerators
* Gtk.HeaderBar
* System icons
* Granite.markup_accel_tooltip

Add a section on GLib.Action

---

writing-apps/code-style.md

This has come up a couple of times, but we don't yet have formal docs for it so here we go

Code Style: Add string formatting section

---

writing-apps/code-style.md

Related to #46
Really a tiny thing though…

Code Style: Add missing trailing semi-colon

---

writing-apps/our-first-app/README.md

This way, it'll also match the sample meson.build (next page).

Use consistent path to .desktop file

---

appcenter/submission-process.md

Closes https://github.com/elementary/docs/issues/53

Update link to the AppCenter Dashboard GitHub integration

---

apis/actions.md
apis/launchers.md
appcenter/publishing-requirements.md
writing-apps/creating-layouts.md
writing-apps/our-first-app/README.md
writing-apps/our-first-app/packaging.md
writing-apps/our-first-app/the-build-system.md

Add Flatpak Docs

---

apis/actions.md
apis/launchers.md
writing-apps/our-first-app/packaging.md

Use elementary SDK in flatpak

---

apis/launchers.md
appcenter/publishing-requirements.md
writing-apps/our-first-app/the-build-system.md

Update broken HIG links

---

SUMMARY.md
apis/gresource.md

I didn't include CSS here because there's just a lot to cover

Add a section on GResource covering icons

---

SUMMARY.md
writing-apps/our-first-app/icons.md
writing-apps/our-first-app/the-build-system.md

Separate icons into its own section and mention template

---

writing-apps/our-first-app/icons.md

This fixes a small typo I found while using the docs to create an elementary OS app Valdo(https://github.com/Prince781/valdo) template.

Fix small typo

---

writing-apps/our-first-app/packaging.md

“Normal people” is quite a problematic term when we’re really talking about people. Developers aren’t “abnormal” and one or two of them might even use AppCenter too ;)

Proposal to remove use of the word “normal”

---

SUMMARY.md
writing-apps/logging.md

Moving contributor and developer docs from the website to GitBook
Goes with https://github.com/elementary/website/pull/2844

Import logging docs from website

---

appcenter/publishing-requirements.md

Raised at https://github.com/elementary/appcenter-reviews/pull/142 and something we've been wanting to clarify.

Publishing Requirements: Clarify duplicate apps

---

writing-apps/code-style/class-construction.md

* Remove the mention of Java/C# style construction since we don't cover it and it doesn't matter
* Elaborate a bit more in the intro on why we like GObject-style construction
* Break things into more sections
* A couple more explanations of why things are important

Class Construction: some edits and additions

---

writing-apps/our-first-app/README.md

Remove link to beta developer center

Fix: Removes link to beta devcenter

---

writing-apps/our-first-app/README.md

Fixes #174
Goes with https://github.com/elementary/appcenter/pull/1883

Our First App: update for appstream branding tag

---

appcenter/publishing-updates.md
writing-apps/our-first-app/metadata.md

Document issues tag in release metadata

---

apis/actions.md
apis/color-scheme.md
apis/launchers.md
apis/state-saving.md
appcenter/publishing-requirements.md
writing-apps/code-style/class-construction.md
writing-apps/creating-layouts.md
writing-apps/hello-world.md
writing-apps/our-first-app/README.md
writing-apps/our-first-app/continuous-integration.md
writing-apps/our-first-app/packaging.md
writing-apps/our-first-app/the-build-system.md

Migrate to Gtk4

---

SUMMARY.md
apis/system-settings.md

Add section on linking to System Settings

---

appcenter/publishing-requirements.md

Seems to be removed in https://github.com/elementary/hig/pull/33

publishing-requirements: Remove dead link

---

appcenter/publishing-requirements.md

Change requirements to use AppStream developer tag

---

writing-apps/the-basic-setup.md

Flatpak setup in Basic Setup section allows readers to pick instructions based on their OS version
Fixes #214

Cleanup Flatpak setup in The Basic Setup section

---

writing-apps/our-first-app/translations.md

translations: Correct order of steps

---

writing-apps/our-first-app/packaging.md

https://docs.flatpak.org/en/latest/manifests.html

packaging: change deprecated app-id to id

---

writing-apps/our-first-app/packaging.md

Fixes https://github.com/elementary/docs/issues/125

Copying -> LICENSE
