elementary/docs

writing-apps/code-style.md
There was a syntax error in the first example, and the alternative using properties was much more complex than it needed to be for the simple case of using properties. I've updated the examples to be syntactically correct and show both the simple/advanced way of definining properties.
=> Code Style: Clarify properties section

appcenter/continuous-integration.md
I changed the version on the `.travis.yaml` file to `10.17.01` because with latest LTS ( `v12.18.3` ) it was failing. 
I choose version 10.17.0 because I notices that Planner was working with that version. I haven't tested with others.
Here's the error with LTS ( `v12.18.3` ) :
```
nodegit.target.mk:255: recipe for target 'Release/obj.target/nodegit/src/promise_completion.o' failed
make: *** [Release/obj.target/nodegit/src/promise_completion.o] Error 1
make: Leaving directory '/home/travis/.nvm/versions/node/v12.18.3/lib/node_modules/@elementaryos/houston/node_modules/nodegit/build'
gyp
ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/buil …
```
=> Change node_js version from lts/* to 10.17.0

writing-apps/our-first-app/packaging.md
It seems to be deprecated: https://lintian.debian.org/tags/priority-extra-is-replaced-by-priority-optional.html
=> packaging: Replace priority extra with optional

writing-apps/our-first-app/README.md
I noticed this right after approving the PR. It's best for links to either be actions or the noun of the thing that is being linked to; `here` is not as natural.
=> Legal Stuff: Better resource link copy

apis/state-saving.md, writing-apps/our-first-app/the-build-system.md, writing-apps/our-first-app/translations.md
Fixes #86 
Intentionally doesn't touch the icons part to avoid conflicts with #84 
While we're here, claim that meson is "coffeescript" instead of "text" so we get approximate syntax highlighting. Also, Meson syntax is no spaces before ()
=> Use new Meson paths syntax

apis/launchers.md
Fixes #96.
- Renames "Static Quicklists" to "Actions" to match the FreeDesktop spec
- Refers to "Applications Menu" and "Dock" consistently
- Improves API support table styling
- Explains where launcher actions will actually appear in the OS
- Provides some clarification around action names and icons
- Clearly mentions the `Actions=` line
- Uses `ini` code highlighting for .desktop files
=> Launchers: rework Static Quicklists/Actions

apis/gresource.md
It looks like we need this leading slash for the path name to resolve correctly
=> GResource: include leading slash

writing-apps/our-first-app/icons.md
Fixes #105 
Adds a table with a list of places icons are used
=> Icons: Add 24px

writing-apps/our-first-app/README.md
I heard this key become necessary for monetization in AppCenter for elementary OS 6, but it does not seem to be mentioned in the doc, so I added it here (tell me if it's already written somewhere though).
=> Mention 'x-appcenter-stripe' key

writing-apps/code-style.md
This makes the assertion "parentheses should be preceded with spaces"  
consistent with the gettext example appearing lower on the page.
=> Coding style: don't use spaces for localized strings.

writing-apps/our-first-app/packaging.md
There is a stable version of the runtime now, so this note can be removed.
=> Remove The Note About `daily` Runtime Version

writing-apps/our-first-app/icons.md
I couldn’t see the new icon in the Applications Menu or the Dock without doing this.
=> Add note on refreshing the system’s icon cache

appcenter/markdown-badges.md
We no longer do an automatic redirect, plus let's upsell this a little more and explain why you'd use a badge/what the AppCenter website provides.
=> Markdown Badges: Update to reality

apis/actions.md
Since the class is called `HeaderBar` and not `Headerbar`, the instance should be called `header_bar` and not `headerbar` ;)
=> Rename headerbar to header_bar for consistency

writing-apps/our-first-app/packaging.md
=> docs: remove double space in example command

apis/actions.md, apis/color-scheme.md, apis/gresource.md, apis/launchers.md, apis/notifications.md, apis/state-saving.md, appcenter/markdown-badges.md, writing-apps/code-style/README.md, writing-apps/code-style/class-construction.md, writing-apps/creating-layouts.md, writing-apps/hello-world.md, writing-apps/logging.md, writing-apps/our-first-app/README.md, writing-apps/our-first-app/continuous-integration.md, writing-apps/our-first-app/icons.md, writing-apps/our-first-app/translations.md
This makes the syntax highlighting languages consistent across the board:
- We no longer have to pretend to be C#, because Vala is now supported on GitBook. ([I tested it.](https://darshak-parikh.gitbook.io/untitled/))
- Meson can be reliably faked with `coffeescript`. We already do this on some pages; I just used it everywhere.
- `.desktop` entries can be reliably faked with `ini`.
- EditorConfig [is](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1491) an `ini`.
- Changed `markup` to `xml`. Both work on GitBook, but `xml` is better supported elsewhere, like on GitHub and in text editors.
- AppCenter badge snippets can be highlighted with `markdown` and `html`.
=> Normalize syntax highlighting

README.md
=> Getting Started documentation reworked

appcenter/publishing-requirements.md, appcenter/publishing-updates.md, writing-apps/our-first-app/README.md, writing-apps/our-first-app/packaging.md, writing-apps/our-first-app/the-build-system.md, writing-apps/our-first-app/translations.md
Fixes #7
Fixes #63
Fixes #156
It looks like "AppData" is an outdated term and everything is referred to as "metainfo" now.
The AppStream generator doesn't do anything with GenericName and we never expose it anywhere anyways, so I just left that out. Keywords are also covered in the linked HIG entry, so I think it's nbd if we omit them here.
=> Rework sections on metadata

apis/actions.md, apis/launchers.md, apis/notifications.md
First part of changes proposed in #182. This PR:
1. Updates code snippets (and accompanying text) of Actions, and to a lesser extend Notifications, sections to reflect the latest state of showcase app in [vala-lang/examples](https://github.com/vala-lang/examples/tree/glib-action).
2. Fixes section description and a URL link to freedesktop specification page in the Launchers section.
=> Action and launchers part 1

apis/actions.md, apis/launchers.md
Resolve #179 
Resolve #180
Second part of changes proposed in https://github.com/elementary/docs/pull/182. This PR:
1. Updates Actions sub-section of the Launchers section to include DBus activation and launching of GLib.Actions.
2. Cross-links from Actions section to Launchers section.
=> Action and launchers part 2

writing-apps/the-basic-setup.md
GitHub’s official guide no longer recommends the rsa algorithm, but rather the ed25519 algorithm.
This PR updates the bullet point to the latest algorithm and adds a link to the official guide in the hints section at the end of the bulleted list.
Thanks!
=> Update the-basic-setup.md with the latest ssh algorithm

writing-apps/our-first-app/the-build-system.md
Before this command we say "change into the build directory", so we don't need to explicit the build directory with the "-C" option.
=> Correct ninja comman to uninstall the app

writing-apps/our-first-app/the-build-system.md
Because recent meson warns implicit 'setup' as deprecated like this:
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
=> Explicit 'setup' subcommand of meson

writing-apps/our-first-app/the-build-system.md, writing-apps/our-first-app/translations.md
meson.source_root() was deprecated in 0.56.0, so don't use it in our documentation too.
=> Replace deprecated source_root with project_source_root

writing-apps/creating-layouts.md
Fixes https://github.com/elementary/docs/issues/79
We don't use `_()` syntax anywhere else other then 'Translations 'and 'Boxes and Grids'. Makes sense to leave it to translations page only.
=> Boxes and Grids: don't translate strings
